[context.deploy-preview.environment]
  VUE_APP_MODE = "development"
  ENVERYWHERE_APP_MODE = "development"
[context.master.environment]
  VUE_APP_MODE = "production"
  ENVERYWHERE_APP_MODE = "production"
[context.development.environment]
  VUE_APP_MODE = "development"
  ENVERYWHERE_APP_MODE = "development"
